version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3307'
    environment:
      MYSQL_DATABASE: 'mysql-db'
      MYSQL_USER: 'mysql-user'
      MYSQL_PASSWORD: 'mysql-password'
      MYSQL_ROOT_PASSWORD: 'mysql-root-password'
      MYSQL_DATABASE_HOST: 'db'
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0000:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db